# Generated by Django 5.0.6 on 2024-07-17 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisi', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('AC', 'AC'), ('DE', 'DE')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori_brg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('DE', 'Deactive')], default='AC', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Counter_bagian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_bagian', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('DE', 'Deactive')], default='AC', max_length=2)),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atkapp.divisi')),
            ],
        ),
        migrations.CreateModel(
            name='Master_barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barang', models.CharField(max_length=250)),
                ('harga', models.IntegerField(default=0)),
                ('harga_jual', models.IntegerField()),
                ('status', models.CharField(choices=[('AC', 'Active'), ('DE', 'Deactive')], default='DE', max_length=2)),
                ('kategori_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atkapp.kategori_brg')),
            ],
        ),
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_beli', models.DateTimeField()),
                ('harga', models.IntegerField()),
                ('harga_jual', models.IntegerField(default=0)),
                ('subTotal', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('master_barang_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atkapp.master_barang')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('DE', 'Deactive')], default='AC', max_length=2)),
                ('counter_bagian_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='atkapp.counter_bagian')),
            ],
        ),
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_keluar', models.DateTimeField()),
                ('qty', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('harga_jual', models.IntegerField(default=0)),
                ('counter_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atkapp.counter_bagian')),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atkapp.divisi')),
                ('master_barang_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atkapp.master_barang')),
                ('personal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='atkapp.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Stok_brg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_transaksi', models.DateTimeField()),
                ('qty_terima', models.IntegerField()),
                ('qty_keluar', models.IntegerField()),
                ('stok', models.IntegerField()),
                ('kode', models.IntegerField()),
                ('person', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('master_barang_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atkapp.master_barang')),
            ],
        ),
        migrations.CreateModel(
            name='Temporary_pembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_beli', models.DateTimeField()),
                ('harga', models.IntegerField()),
                ('subTotal', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('master_barang_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atkapp.master_barang')),
            ],
        ),
        migrations.CreateModel(
            name='Temporary_pengeluaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_keluar', models.DateTimeField()),
                ('qty', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('harga_jual', models.IntegerField(default=0)),
                ('counter_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atkapp.counter_bagian')),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atkapp.divisi')),
                ('master_barang_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atkapp.master_barang')),
                ('personal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='atkapp.personal')),
            ],
        ),
    ]
