# Generated by Django 5.0.6 on 2024-07-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stok_brg',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='stok_brg',
            name='person',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
